# Packages uploading
install.packages(c("vegan", "ggmap"))
library(vegan)
library(ggmap)

# Data uploading
data("BCI")
data(BCI.env)

# EDA 
str(BCI)
summary(BCI)
hist(colSums(BCI), main = "Distribution of Species Counts")
shannon <- diversity(BCI)
shannon

library(tidyr)
library(dplyr)
library(broom)


# NDMS ordination
nmds_result <- metaMDS(BCI, distance = "bray", k = 3)
ordiplot(nmds_result, type = "t")
text(nmds_result, display = "sites")
stressplot(nmds_result)
nmds_result$stress

# Ordination interactions with enviromnet 
ef <- envfit(nmds_result, BCI.env)
ordiplot(nmds_result, type = "n")
plot(ef)
plot(nmds_result, display = "sites")
plot(ef, p.max = 0.05) # display significantly clustered variables
# Visualization of factors
utm_ord <- ordisurf(nmds_result, BCI.env$UTM.EW, method = "REML", plot = FALSE)
plot(utm_ord)
orditorp(nmds_result,display = "species")
hab_ord <- ordisurf(nmds_result, as.integer(factor(BCI.env$Habitat)), method = "REML", plot = FALSE)
plot(hab_ord)
orditorp(nmds_result, display = "species")

#Conclusion
#Using distances based on species abundances, we explored floral composition's
#relationship with environmental factors: stream presence, habitat type, and environmental
#heterogeneity. The visualization revealed no significant correlation between
#stream presence or environmental heterogeneity and species presence. 
#However, distinct species clusters emerged based on habitat type (p=0.001), 
#forming two major groups: swampy and young habitats, alongside old habitats. 
#Additionally, all five habitat types formed separate clusters, differing in species composition.
